[multipage-level=2]
== Building a case for formal engagement in GBIF

[NOTE.objectives]
*Objectives*

In this module, we will:

* describe what is involved in the modes of formal GBIF Participation and the benefits this brings
* understand how individuals, institutions and countries can participate in GBIF
* identify and prioritize stakeholders to engage in moving towards GBIF Participation

=== Benefits of GBIF Participation and of establishing a Participant Node

[NOTE.presentation]
In this video (12:26), you will review ... used in this course. 
If you are unable to watch the embeded Vimeo video, you can download it locally. (MP4 - 44.5 MB)

video::FZAF5Sy8Nsc[youtube, height=540, width=960, align=center]


[NOTE.activity]
Become familiar with the ...



=== Process for becoming a GBIF Participant

[NOTE.activity]
In this section, you will learn what is required to become a member of GBIF.

****
Review the information on the GBIF website about https://www.gbif.org/become-member[how to become a member^].
****

=== Key audiences to engage in GBIF at the national level



=== Participatory approach to establish a Participant node

==== sub sub topic

Paragraph1, sentence1.
Sentence 2.
Sentence 3.

“Paragraph2, sentence1.
Sentence 2.
Sentence 3.
