[multipage-level=2]
== Building a case for formal engagement in GBIF

[NOTE.objectives]
*Objectives*

In this module, we will:

* describe what is involved in the modes of formal GBIF Participation and the benefits this brings
* understand how individuals, institutions and countries can participate in GBIF
* identify and prioritize stakeholders to engage in moving towards GBIF Participation

=== Understanding GBIF's value

[NOTE.activity]
The starting point for building a case for a country or international organization to formally participate in GBIF is to understand the value of GBIF as data infrastructure and an international network. 
In this section, we will explore GBIF’s relevance through a series of videos focusing on the contributions to research and policy thematic areas. 
While watching these, consider and take note of rationale that could help you to build a case for participation in the GBIF network.
You will need these rationale for the activities later in the course.



[NOTE.presentation]
In this video (10:08) from the GBIF Impact and Action Symposium, 2021, GBIF's Executive Secretary, Dr. Joe Miller, discusses GBIF's relevance for science and policy. 
If you are unable to watch the embeded Vimeo video, you can download it locally.

video::FZAF5Sy8Nsc[youtube, height=540, width=960, align=center]




=== Process for becoming a GBIF Participant

[NOTE.activity]
In this section, you will learn what is required to become a member of GBIF.

****
Review the information on the GBIF website about https://www.gbif.org/become-member[how to become a member^].
****

In the https://docs.gbif.org/course-introduction-to-gbif/en/introduction-to-gbif-participant-nodes.html[Introduction to GBIF Participant nodes section] of the pre-requisite course, we discussed the modes of formal Participation in GBIF as an intergovernmental network and research infrastructure. 

=== Key audiences to engage in GBIF at the national level



=== Participatory approach to establish a Participant node


=== Exercise 1: Identifying and prioritizing stakeholders to engage towards GBIF Participation


=== Exercise 2: Selecting rationale and arguments


==== sub sub topic

Paragraph1, sentence1.
Sentence 2.
Sentence 3.

“Paragraph2, sentence1.
Sentence 2.
Sentence 3.
