[description]
== Course description

****
This course aims to support teams working on GBIF funded projects, observers and other interested participants in the first stages of establishing a GBIF Participant node. 

Topics include:

* Benefits of GBIF Participation and of estblishing a Participant Node
* Process for joining GBIF
* Key audiences to engage in GBIF at a national level
* Participatory approach to establishing a Participant node
* Nodes models and governance
* Planning and reporting documents for a GBIF Participant node
* Ongoing support for developing Participant nodes


This course is comprised of video instruction paired with quizzes and practical exercises. Course participants will be put in groups and social interaction is encouraged. Completing the four practicial exercises, providing peer feedback within your group, and attending two live question and answer sessions are compulsory to successfully completing the course and receiving certification. 
****

=== Audience
This course is for...

=== Prerequisites

. https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^]

. Commitment to completing the course within the allocated time-frame and to supporting your peers in the group work

=== Learning objectives

* Objective
* Objective
* Objective
* Objective

// inlude if needed, otherwise remove
=== Certification

Upon successful completion of the course and successful assessment of assignments (by trainers/mentors), participants have the opportunity to receive an official certification in the form of a Mozilla Open Badge.

Participants are required to submit ... and it is scored against the educational rubrics for the course. 

* An overall score of ??? earns a BASIC badge
* An overall score of ??? earns an ADVANCED badge
