[description]
== Course description

****
This course aims to support teams working on GBIF funded projects, observers and other interested participants in the first stages of building a case for formal Participation in GBIF and establishing a Participant node. 

Topics include:

* Benefits of GBIF Participation and of establishing a Participant Node
* Process for joining GBIF
* Key audiences to engage in GBIF at a national level
* Participatory approach to establishing a Participant node
* Ongoing support towards formal GBIF Participation and for establishing nodes


This course is comprised of videos and documentation paired with quizzes and practical exercises. 
Course participants will be put into peer groups and social interaction is encouraged. 
Completing the practicial exercises, providing peer feedback within your group, and attending two live question and answer sessions are compulsory to successfully completing the course and receiving certification. 
****

=== Audience
This course is aimed at teams engaged in GBIF's capacity development programmes based in countries or organizations that are not yet formal GBIF Participants. Encouraging national Participation and the establishment of a Participant node is a good way to ensure the sustainabilty of efforts started through capacity development projects focused on biodiversity data mobilization and use.

=== Prerequisites

. Completing the https://docs.gbif.org/course-introduction-to-gbif[Introduction to GBIF course^]

All participants must commit to completing the course within the allocated time-frame and to supporting your peers in the group work.

// === Learning objectives

// inlude if needed, otherwise remove
=== Certification

Upon successful completion of the course and successful assessment of assignments (by mentors), participants have the opportunity to receive an official certification.

Participants are required to submit their exercises and attend the two live sessions to receive certification.
