== Files for download

All files for the course may be downloaded from this page. 
Or if you prefer, all files are linked individually throughout the course as they occur in the curriculum. 
The video files are embedded throughout the course, as well, and play from YouTube or Vimeo. Subtitles are available when playing from YouTube and Vimeo for most videos. 
If you have difficulty accessing the embedded videos, please download the mp4 files to play them locally on your computer.

=== Videos
The videos are narrated in English. Subtitles are not available for the downloaded videos.

link:../videos/linkname.zip[linkname.zip,opts=download] (??.? MB)

=== Exercise sheets
There are four exercise sheets for this course. They are Word document templates.

The first is for keeping track of your answers to the self-study activities in the section on Building a case for engagement in GBIF. You are welcome to discuss your answers with your group and during the live sessions. 

link:../course-docs/A-Exercise-sheet-EN.docx[Download the self-study activity sheet] (59 KB)


The next three correspond to the practical exercises that you will complete in the section on Engaging stakeholders towards establishing a node. You will need to submit these to your peer-learning group to receive the certificate of completion for the course.


This link link:../course-docs/Module-1-Exercise-sheet-EN.docx[will download Exercise Sheet 1,opts=download] (71.9 MB) for the first module. 
The exercises sheets are written in English and should be completed in English.
